import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar/Navbar";
import { FooterSection } from "@/components/footer/Footer";
import { Toaster } from "sonner";
import Providers from "@/redux/features/Providers";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Getavails - Talent Booking Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${interFont.variable} ${geistMono.variable} antialiased`}
        style={{
          fontFamily: "Inter, sans-serif",
        }}
      >
        <Providers>
          <Toaster position='top-center' />
          <Navbar />
          {children}
          <FooterSection />
        </Providers>
      </body>
    </html>
  );
}
