import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/dashboard/sidebar/AppSide";
import Header from "@/components/dashboard/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Getavails - Talent Booking Platform Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <div
            className='flex min-h-screen bg-bodyBg w-full'
            style={{
              background: "linear-gradient(180deg, #315D62 0%, #6ECEDA 100%)",
            }}
          >
            <AppSidebar />
            <main className='relative flex-1 min-h-screen w-full bg-white p-6'>
              <SidebarTrigger
                className={`text-black absolute top-2 md:left-2 right-2`}
              />
              <Header />
              {children}
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
